[workspace]
authors = ["Hiroyuki Okada <okdhryk@gmail.com>"]
channels = ["robostack-staging", "conda-forge"]
name = "pixi"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-desktop-full = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
numpy = "*"
ros-humble-nav2-common = ">=1.1.18,<2"
ros-humble-nav2-bringup = ">=1.1.18,<2"
ros-humble-nav2-costmap-2d = ">=1.1.18,<2"
ros-humble-nav2-core = ">=1.1.18,<2"




