authors = ["Hiroyuki Okada <okdhryk@gmail.com>"]
name = "kachaka-ros2"
version = "0.1.0"
description = "ROS 2 + Kachaka in a pixi environment"
channels = ["robostack-staging", "conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
ros-humble-desktop-full = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
#python = "3.12.*"
numpy = "*"
portaudio = "*"
ros-humble-nav2-common = ">=1.1.18,<2"
ros-humble-nav2-bringup = ">=1.1.18,<2"
ros-humble-nav2-costmap-2d = ">=1.1.18,<2"
ros-humble-nav2-core = ">=1.1.18,<2"

[host-dependencies]
pip = "*"

[pypi-dependencies]
sounddevice = "*"
pyyaml = "*"


[tasks]
# 1) VOICEVOX のエンジン資産（ONNX Runtime / OpenJTalk 辞書 / モデル）を取得
get_assets = "bash scripts/get_voicevox_assets.sh"
